name: Deploy Edge

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./backend/python-model-service
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          daymonpollet/smart-alarm-cloud-computing:latest
          daymonpollet/smart-alarm-cloud-computing:${{ github.sha }}

  deploy-canary:
    needs: build-and-push
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Pi
      run: |
        # Ensure the deployment and service exist
        kubectl apply -f k8s/canary/deployment.yaml
        kubectl apply -f k8s/service.yaml
        
        # Update the image
        kubectl set image deployment/sleep-model-deployment sleep-model=daymonpollet/smart-alarm-cloud-computing:${{ github.sha }}
        
        # Wait for rollout
        kubectl rollout status deployment/sleep-model-deployment

    
    - name: Promote to Production
      run: |
        kubectl set image deployment/sleep-model-deployment sleep-model=daymonpollet/smart-alarm-cloud-computing:${{ github.sha }}
        kubectl rollout status deployment/sleep-model-deployment
        kubectl delete -f k8s/canary/deployment.yaml
